# Generated by Django 2.2.24 on 2022-09-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCodeModel',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Area Covering Name')),
                ('enabled', models.BooleanField()),
                ('area_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.PostalCodeModel')),
            ],
        ),
    ]
