# Generated by Django 2.2.24 on 2022-08-30 06:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import reciever.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConversionTable',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecievingPotholeImages',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('area', models.IntegerField()),
                ('number', models.IntegerField()),
                ('cordinate_X', models.FloatField()),
                ('cordinate_Y', models.FloatField()),
                ('RCreated_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('rawImageUrl', models.TextField(default='None')),
                ('maskedImageUrl', models.TextField(default='None')),
                ('point', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', geography=True, srid=4326)),
                ('premise', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('park', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('airport', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('natural_feature', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('plus_code', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('subpremise', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_1', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_2', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_3', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_4', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_5', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('locality', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('colloquial_area', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_1', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_2', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_3', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_4', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_5', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('intersection', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('route', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('formatted_address', models.TextField(blank=True, default='None', max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pothole Mapping',
            },
        ),
        migrations.CreateModel(
            name='ProvidedApis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('user_id', models.UUIDField(editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('totalRequests', models.PositiveIntegerField(default=0)),
                ('avgResponseMs', models.PositiveIntegerField(default=0)),
                ('failedRequestsCount', models.PositiveIntegerField(default=0)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciever.AvailableApi')),
            ],
        ),
        migrations.CreateModel(
            name='PotholeUpdationImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_image', models.ImageField(upload_to=reciever.models.UpdatedImageofPotholeImages)),
                ('cordinate_X', models.FloatField()),
                ('cordinate_Y', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_filled', models.BooleanField(default=True)),
                ('checked', models.BooleanField(default=False)),
                ('distance', models.IntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', geography=True, srid=4326)),
                ('premise', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('park', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('airport', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('natural_feature', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('plus_code', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('subpremise', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_1', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_2', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_3', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_4', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('sublocality_level_5', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('locality', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('colloquial_area', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_1', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_2', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_3', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_4', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('administrative_area_level_5', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('intersection', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('route', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('formatted_address', models.TextField(blank=True, default='None', max_length=1000, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated', to='reciever.RecievingPotholeImages')),
            ],
        ),
    ]
