# Generated by Django 2.2.24 on 2022-08-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0002_ab'),
    ]

    operations = [
        migrations.AddField(
            model_name='ab',
            name='token',
            field=models.CharField(max_length=100, null=True, default=None),
        ),
    ]
