# Generated by Django 2.2.24 on 2022-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0003_ab_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='providedapis',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
