# Generated by Django 2.2.24 on 2022-09-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0004_providedapis_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='providedapis',
            name='maxQuota',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
