# Generated by Django 2.2.24 on 2022-09-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0006_auto_20220905_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providedapis',
            name='totalRequestPerMin',
        ),
    ]
