# Generated by Django 2.2.24 on 2022-10-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0008_auto_20220905_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='recievingpotholeimages',
            name='type',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
