# Generated by Django 2.2.24 on 2022-10-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0009_recievingpotholeimages_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableapi',
            name='group',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availableapi',
            name='iconHex',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availableapi',
            name='iconImage',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='providedapis',
            name='api',
        ),
        migrations.AddField(
            model_name='providedapis',
            name='api',
            field=models.ManyToManyField(default=None, to='reciever.AvailableApi'),
        ),
    ]
