# Generated by Django 2.2.24 on 2022-10-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0010_auto_20221015_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidedApiPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maxQuota', models.PositiveIntegerField(default=50)),
                ('maxQuotaPerMinute', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedApisStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('DEL', 'Deleted'), ('RUN', 'Running'), ('STOP', 'Stopped')], max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='availableapi',
            name='group',
        ),
        migrations.RemoveField(
            model_name='providedapis',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='providedapis',
            name='maxQuota',
        ),
        migrations.RemoveField(
            model_name='providedapis',
            name='maxQuotaPerMinute',
        ),
        migrations.AlterField(
            model_name='providedapis',
            name='api',
            field=models.ManyToManyField(to='reciever.AvailableApi'),
        ),
        migrations.AddField(
            model_name='providedapis',
            name='api_stat',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProvidedApisStatus'),
        ),
        migrations.AddField(
            model_name='providedapis',
            name='plan',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProvidedApiPlan'),
        ),
    ]
