# Generated by Django 2.2.24 on 2022-10-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0011_auto_20221015_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableapi',
            name='group',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providedapis',
            name='api_stat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProvidedApisStatus'),
        ),
        migrations.AlterField(
            model_name='providedapis',
            name='plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProvidedApiPlan'),
        ),
    ]
