# Generated by Django 2.2.24 on 2022-10-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0012_auto_20221016_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providedapis',
            name='api_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProvidedApisStatus'),
        ),
        migrations.AlterField(
            model_name='providedapisstatus',
            name='stat',
            field=models.CharField(choices=[('DEL', 'Deleted'), ('RUN', 'Running'), ('STOP', 'Stopped')], default='DEL', max_length=4),
        ),
    ]
