# Generated by Django 2.2.24 on 2022-10-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0013_auto_20221018_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providedapis',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProvidedApiPlan'),
        ),
    ]
