# Generated by Django 2.2.24 on 2022-10-28 16:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import reciever.models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0014_auto_20221018_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImagesBarricade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(blank=True, verbose_name='Bucket Image Link')),
                ('image', models.ImageField(upload_to=reciever.models.UpdatedImageofPotholeImages)),
                ('number', models.IntegerField(default=None, null=True)),
                ('verified', models.BooleanField(blank=True, default=None, null=True)),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedImagesPothole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reciever.models.UpdatedImageofPotholeImages)),
                ('image_url', models.TextField(blank=True, null=True, verbose_name='Bucket Image Link')),
                ('area', models.FloatField(default=None, null=True)),
                ('number', models.IntegerField(default=None, null=True)),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), size=None), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedImagesWaterLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterlogging', models.BooleanField(blank=True, default=None, null=True)),
                ('verified', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recievingpotholeimages',
            name='type',
        ),
        migrations.AddField(
            model_name='recievingpotholeimages',
            name='barricade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProcessedImagesBarricade'),
        ),
        migrations.AddField(
            model_name='recievingpotholeimages',
            name='pothole',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProcessedImagesPothole'),
        ),
        migrations.AddField(
            model_name='recievingpotholeimages',
            name='waterlogging',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProcessedImagesWaterLogging'),
        ),
    ]
