# Generated by Django 2.2.24 on 2022-11-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0016_recievingpotholeimages_showurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recievingpotholeimages',
            name='area',
        ),
        migrations.RemoveField(
            model_name='recievingpotholeimages',
            name='number',
        ),
    ]
