# Generated by Django 2.2.24 on 2022-11-15 19:12

from django.db import migrations, models
import reciever.models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0018_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zipcode',
        ),
        migrations.AddField(
            model_name='processedimageswaterlogging',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=reciever.models.UpdatedImageofPotholeImages),
        ),
        migrations.AddField(
            model_name='processedimageswaterlogging',
            name='image_url',
            field=models.TextField(blank=True, verbose_name='Bucket Image Link'),
        ),
    ]
