# Generated by Django 2.2.24 on 2022-12-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0020_auto_20221205_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='recievingpotholeimages',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
