# Generated by Django 2.2.24 on 2022-12-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0021_recievingpotholeimages_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recievingpotholeimages',
            name='verified',
        ),
    ]
