# Generated by Django 2.2.24 on 2022-12-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0022_remove_recievingpotholeimages_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimagespothole',
            name='verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
