# Generated by Django 2.2.24 on 2023-04-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0023_processedimagespothole_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Xyzd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciever.ProvidedApis')),
                ('veh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.Vehicles')),
            ],
            options={
                'verbose_name': 'Multi Token',
            },
        ),
    ]
