# Generated by Django 2.2.24 on 2023-04-19 20:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0025_providedapiplan_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='providedapis',
            name='locality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
