# Generated by Django 2.2.24 on 2023-05-10 04:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0026_providedapis_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedimagesroadasset',
            name='image',
        ),
        migrations.AddField(
            model_name='processedimagesroadasset',
            name='classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='recievingpotholeimages',
            name='roadasset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reciever.ProcessedImagesRoadAsset'),
        ),
    ]
