# Generated by Django 2.2.24 on 2023-07-01 05:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0028_childheadersender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('0', 'IN CABIN'), ('1', 'BLACK'), ('2', 'OK')], default=None, max_length=10, null=True)),
                ('formatted_address', models.TextField(blank=True, default='None', max_length=1000, null=True)),
                ('status_process', models.CharField(choices=[('READY', 'READY FOR PROCESS'), ('DL_S', 'DOWNLOADING IN ML SERVER'), ('IN_P', 'IN PROCESS'), ('PROC', 'PROCESSED'), ('FAIL', 'FAILED')], default=None, max_length=5, null=True)),
                ('deviceImei', models.CharField(default=None, max_length=50, null=True)),
                ('ignition', models.CharField(default=None, max_length=10, null=True)),
                ('image_id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=300, null=True, unique=True)),
                ('images_url', models.TextField(blank=True, verbose_name='Bucket Image Link')),
                ('short_country_code', models.CharField(default='IND', max_length=20)),
                ('country', models.CharField(default='None', max_length=255)),
                ('state', models.CharField(default='NA', max_length=255)),
                ('district', models.CharField(default='NA', max_length=255)),
                ('type_1', models.CharField(default='NA', max_length=255)),
                ('type_2', models.CharField(default='NA', max_length=255)),
                ('type_3', models.CharField(default='NA', max_length=255)),
                ('cordinate_X', models.FloatField()),
                ('cordinate_Y', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('device_created_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', geography=True, srid=4326)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('car_speed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Processed Road Images',
                'ordering': ('created_date',),
                'managed': False,
            },
        ),
    ]
