# Generated by Django 2.2.24 on 2023-07-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciever', '0029_potholeimages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='potholeimages',
            table='images_potholeimages',
        ),
    ]
