# Generated by Django 2.2 on 2020-10-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('request_type', models.CharField(choices=[('ABOX', 'Android Bounding Box'), ('WBOX', 'Web Bounding Box'), ('CNTR', 'Country'), ('NTRB', 'Near By'), ('GNRL', 'Generic Leaflet'), ('GNLL', 'Generic Leaflet with Location'), ('DCNT', 'Distict Country Count')], max_length=4)),
                ('ip_address', models.CharField(blank=True, max_length=220, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
