# Generated by Django 2.2 on 2020-10-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_receiveranalytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiverAnalytics',
        ),
    ]
