# Generated by Django 2.2 on 2020-10-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_baseanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverAnalytics',
            fields=[
                ('baseanalytics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.BaseAnalytics')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
                ('request_type', models.CharField(choices=[('ABOX', 'Android Bounding Box'), ('WBOX', 'Web Bounding Box'), ('CNTR', 'Country'), ('NTRB', 'Near By'), ('GNRL', 'Generic Leaflet'), ('GNLL', 'Generic Leaflet with Location'), ('DCNT', 'Distict Country Count')], max_length=4)),
            ],
            bases=('analytics.baseanalytics',),
        ),
    ]
