# Generated by Django 2.2 on 2020-10-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_receiveranalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveranalytics',
            name='request_type',
            field=models.CharField(choices=[('ABOX', 'Android Bounding Box'), ('WBOX', 'Web Bounding Box'), ('CNTR', 'Country'), ('NTRB', 'Near By'), ('GNRL', 'Generic Leaflet'), ('GNLL', 'Generic Leaflet with Location'), ('DCNT', 'Distinct Country Count'), ('EABX', 'Exception Android Bounding Box'), ('EWBX', 'Exception Web Bounding Box'), ('ECNT', 'Exception Country'), ('ENTR', 'Exception Near By'), ('EGNL', 'Exception Generic Leaflet'), ('EGLL', 'Exception Generic Leaflet with Location'), ('EDCT', 'Exception Distinct Country Count')], max_length=4),
        ),
    ]
