# Generated by Django 2.2 on 2020-10-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20201014_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveranalytics',
            name='country',
        ),
    ]
