# Generated by Django 2.2 on 2020-10-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20201014_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grafana_api_list',
            options={'verbose_name': 'Api Index', 'verbose_name_plural': 'Api Index'},
        ),
        migrations.AlterModelOptions(
            name='grafana_server_list',
            options={'verbose_name': 'App Index', 'verbose_name_plural': 'App Index'},
        ),
        migrations.AlterModelOptions(
            name='receiveranalytics',
            options={'verbose_name': 'Receiver Analytics', 'verbose_name_plural': 'Receiver Analytics'},
        ),
    ]
