# Generated by Django 2.2 on 2020-10-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_auto_20201014_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveranalytics',
            name='baseanalytics_ptr',
        ),
        migrations.DeleteModel(
            name='BaseAnalytics',
        ),
        migrations.DeleteModel(
            name='ReceiverAnalytics',
        ),
    ]
