# Generated by Django 2.2.24 on 2022-08-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220823_0054'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_user',
        ),
    ]
